'use client'

import { FormEvent, useState } from 'react'
import { Send } from 'lucide-react'
import type { TableRow } from '@/lib/database.types'
import { formatDateTime } from '@/lib/format'

type Ticket = TableRow<'support_tickets'> & { messages: TableRow<'support_messages'>[] }

export default function ApplicantMessages({ initialTickets, userId }: { initialTickets: Ticket[]; userId: string }) {
  const [tickets, setTickets] = useState(initialTickets); const [selectedId, setSelectedId] = useState(initialTickets[0]?.id ?? ''); const [draft, setDraft] = useState(''); const [subject, setSubject] = useState(''); const [creating, setCreating] = useState(!initialTickets.length); const [error, setError] = useState('')
  const selected = tickets.find((ticket) => ticket.id === selectedId)
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); const url = creating ? '/api/support/tickets' : `/api/support/tickets/${selectedId}/messages`; const payload = creating ? { subject, message: draft, priority: 'normal' } : { message: draft, internal: false }; const response = await fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) { setError(result.error || 'Unable to send message'); return }; const now = new Date().toISOString(); if (creating) { const ticket: Ticket = { id: result.id, user_id: userId, subject, status: 'open', priority: 'normal', assigned_to: null, created_at: now, updated_at: now, resolved_at: null, messages: [{ id: crypto.randomUUID(), ticket_id: result.id, sender_user_id: userId, body: draft, is_internal: false, created_at: now }] }; setTickets((items) => [ticket, ...items]); setSelectedId(ticket.id); setCreating(false); setSubject('') } else { setTickets((items) => items.map((ticket) => ticket.id === selectedId ? { ...ticket, messages: [...ticket.messages, { id: result.id, ticket_id: ticket.id, sender_user_id: userId, body: draft, is_internal: false, created_at: now }] } : ticket)) }; setDraft('') }
  return <div className="grid min-h-[620px] overflow-hidden rounded-3xl border border-[#dfe3da] bg-white lg:grid-cols-[320px_1fr]"><aside className="border-b border-[#dfe3da] p-4 lg:border-b-0 lg:border-r"><button onClick={() => setCreating(true)} className="mb-4 w-full rounded-xl bg-[#17351f] px-4 py-3 text-sm font-bold text-white">New support ticket</button><div className="space-y-2">{tickets.map((ticket) => <button key={ticket.id} onClick={() => { setCreating(false); setSelectedId(ticket.id) }} className={`w-full rounded-xl p-3 text-left ${selectedId === ticket.id && !creating ? 'bg-[#eff4ea]' : 'hover:bg-[#f7f8f3]'}`}><strong className="block text-sm">{ticket.subject}</strong><span className="mt-1 block text-xs capitalize text-[#667069]">{ticket.status} · {ticket.messages.length} messages</span></button>)}</div></aside><section className="flex min-w-0 flex-col">{creating ? <header className="border-b border-[#dfe3da] p-5"><h2 className="text-xl font-bold">Start a conversation</h2><p className="text-sm text-[#667069]">Tell the support team what you need help with.</p></header> : selected ? <header className="border-b border-[#dfe3da] p-5"><h2 className="text-xl font-bold">{selected.subject}</h2><p className="text-sm capitalize text-[#667069]">Ticket status: {selected.status}</p></header> : null}<div className="flex flex-1 flex-col gap-3 bg-[#fafbf8] p-5">{!creating && selected?.messages.map((message) => { const mine = message.sender_user_id === userId; return <article key={message.id} className={`max-w-[78%] rounded-2xl px-4 py-3 text-sm leading-6 ${mine ? 'ml-auto bg-[#17351f] text-white' : 'bg-white ring-1 ring-[#dfe3da]'}`}><p>{message.body}</p><time className="mt-1 block text-xs opacity-60">{formatDateTime(message.created_at)}</time></article> })}</div><form onSubmit={submit} className="space-y-3 border-t border-[#dfe3da] p-4">{creating && <input value={subject} onChange={(event) => setSubject(event.target.value)} placeholder="Ticket subject" className="h-11 w-full rounded-xl border border-[#cfd6cc] px-3 text-sm" required />}<div className="flex gap-2"><textarea value={draft} onChange={(event) => setDraft(event.target.value)} className="min-h-16 flex-1 rounded-xl border border-[#cfd6cc] p-3 text-sm" placeholder="Write your message…" required /><button className="grid size-12 shrink-0 place-items-center self-end rounded-full bg-[#17351f] text-white" aria-label="Send"><Send className="size-4" /></button></div>{error && <p className="text-sm text-rose-700">{error}</p>}</form></section></div>
}
