'use client'
import { FormEvent, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { ArrowLeft, Download, FileText, UploadCloud, X } from 'lucide-react'
import StatusBadge from '@/components/dashboard/StatusBadge'
import type { Requirement } from '@/lib/models'

export default function RequirementDetail({ requirement, backHref = '/dashboard/requirements', backLabel = 'Back to requirements' }: { requirement: Requirement; backHref?: string; backLabel?: string }) {
  const router = useRouter(); const [file, setFile] = useState<File | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [text, setText] = useState(requirement.responseText || '')
  const fileAllowed = requirement.submissionType !== 'text'; const textAllowed = requirement.submissionType !== 'file'
  async function upload(event: FormEvent) { event.preventDefault(); if (!file) return; setBusy(true); setError(''); const form = new FormData(); form.set('documentType', requirement.title); form.set('file', file); const response = await fetch('/api/documents', { method: 'POST', body: form }); const result = await response.json(); if (!response.ok) { setError(result.error || 'Upload failed'); setBusy(false); return }; setFile(null); setBusy(false); router.refresh() }
  async function saveText() { if (!text.trim()) return; setBusy(true); setError(''); const response = await fetch(`/api/requirements/${requirement.id}/text`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text }) }); const result = await response.json(); if (!response.ok) { setError(result.error || 'Unable to save your response'); setBusy(false); return }; setBusy(false); router.refresh() }
  return <div className="page-stack narrow-page"><Link className="back-link" href={backHref}><ArrowLeft />{backLabel}</Link><section className="adm-card requirement-detail-card"><div className="detail-title"><div><p className="eyebrow-dark">Application requirement</p><h2>{requirement.title}</h2><p>{requirement.description}</p></div><StatusBadge status={requirement.status} /></div><div className="detail-grid"><form onSubmit={upload} className="upload-panel"><h3>{requirement.submissionType === 'text' ? 'Write your response' : requirement.document ? 'Replace document' : 'Upload document'}</h3><p className="guidance-line"><strong>Guidance:</strong> {requirement.guidance || 'Follow the instructions shown for this requirement.'}</p>{textAllowed && <label className="mt-4 block text-sm font-semibold">Your response<textarea value={text} onChange={(event) => setText(event.target.value)} onBlur={saveText} className="mt-2 min-h-32 w-full rounded-xl border border-[#cfd6cc] p-3 text-sm outline-none focus:border-[#64806b]" placeholder="Write your response here" /></label>}{fileAllowed && <><label className={`drop-zone ${file ? 'has-file' : ''}`} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); setFile(event.dataTransfer.files[0] || null) }}><input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={(event) => setFile(event.target.files?.[0] || null)} /><span className="upload-icon"><UploadCloud /></span><strong>Drop a document here</strong><span>or <em className="text-button">choose a file</em></span><small>{requirement.accepted || 'PDF, JPG, PNG or WebP up to 10 MB'}</small></label>{file && <div className="selected-files"><div><span><FileText /></span><p><strong>{file.name}</strong><small>{(file.size / 1024 / 1024).toFixed(2)} MB</small></p><button type="button" onClick={() => setFile(null)}><X /></button></div></div>}{file && <button disabled={busy} className="adm-button button-primary full-button" type="submit"><UploadCloud />{busy ? 'Uploading securely…' : 'Upload document'}</button>}</>}{error && <p className="form-message warning-message">{error}</p>}</form><aside className="document-summary"><h3>Current submission</h3>{requirement.responseText && <div className="no-file"><strong>Written response</strong><p className="mt-2 whitespace-pre-wrap">{requirement.responseText}</p></div>}{requirement.document ? <div className="current-file"><span><FileText /></span><div><strong>{requirement.document.name}</strong><small>Review status: {requirement.document.status.replaceAll('_', ' ')}</small></div></div> : !requirement.responseText && <div className="no-file">No submission has been provided yet.</div>}{requirement.document?.previewUrl && <a href={requirement.document.previewUrl} target="_blank" rel="noreferrer" className="adm-button button-secondary full-button"><Download />View submission</a>}</aside></div></section></div>
}
