import Link from 'next/link'
import { ArrowLeft, Check, CreditCard, LockKeyhole } from 'lucide-react'
import { requireUser } from '@/lib/auth'
import { getApplicantAccount } from '@/lib/data/application'

export default async function PaymentPage() {
  const user = await requireUser()
  const { application } = await getApplicantAccount(user.id)
  const paid = application?.payment_status === 'paid'
  return <div className="page-stack narrow-page"><Link className="back-link" href="/dashboard/settings"><ArrowLeft />Back to settings</Link><section className="page-intro"><div><p className="eyebrow-dark">Final-stage payment</p><h2>Payment is collected once, before the final stage.</h2><p>Your payment status is loaded from your application record.</p></div></section><div className="payment-grid"><section className="adm-card payment-summary"><span className="payment-icon"><CreditCard /></span><h2>Application processing</h2><p>The exact stage and final amount are controlled by the operations team.</p><div><span>Current payment status</span><strong className="capitalize">{application?.payment_status.replaceAll('_', ' ') || 'Not configured'}</strong></div><div><span>Amount</span><strong>{application?.payment_amount == null ? 'To be confirmed' : `₦${Number(application.payment_amount).toLocaleString()}`}</strong></div><div><span>Application stage</span><strong className="capitalize">{application?.status.replaceAll('_', ' ') || 'Not started'}</strong></div></section><section className="adm-card payment-action">{paid ? <div className="payment-complete"><span><Check /></span><h2>Payment recorded</h2><p>Your database record confirms payment and the final stage is available.</p></div> : <><span className="card-eyebrow">Current account state</span><h2>{application?.payment_status === 'due' ? 'Payment is now due' : 'No payment is required now'}</h2><p>{application?.payment_status === 'due' ? 'Contact support if you need assistance with the configured payment process.' : 'The operations team will update this page when your application reaches the payment stage.'}</p><small><LockKeyhole />Payment state is protected by your authenticated application record.</small></>}</section></div></div>
}
