import Link from 'next/link'
import { ArrowLeft, Bell, FileCheck2, MessageCircle, ShieldCheck, Users } from 'lucide-react'

const steps = [
  { title: '1. Confirm the applicant account', text: 'Applicants join through Supabase Auth. Their public applicant record is created only after they confirm their email address. Find them in Students or Applications.', icon: Users },
  { title: '2. Open the applicant record', text: 'Click an applicant name from Students, Applications, a document card, or a support conversation. Their record brings their application details, selected universities, and uploaded files into one place.', icon: Users },
  { title: '3. Review every document', text: 'Open Documents for the full queue, or work from a specific applicant record. Preview the private file, add an internal note for staff, then approve, reject, or request a resubmission. Add a clear message when the applicant needs to act.', icon: FileCheck2 },
  { title: '4. Handle support conversations', text: 'Use Support Inbox to read ticket history and reply. Set the next status to open, pending, or resolved so the queue accurately reflects the work left to do.', icon: MessageCircle },
  { title: '5. Publish updates', text: 'In Updates, choose All students for a normal platform-wide announcement. For a university update, search for and select the university first—only applicants who selected it will see the post and receive a notification.', icon: Bell },
  { title: '6. Keep access controlled', text: 'Only active admins can publish updates and access administration features. Support agents can work in their support workspace. Use Staff to review team access and Audit logs to understand sensitive activity.', icon: ShieldCheck },
]

export default function OperationsGuidePage() {
  return <div className="mx-auto max-w-5xl"><Link href="/admin/help" className="mb-6 inline-flex items-center gap-2 text-sm font-bold text-[#31583b]"><ArrowLeft className="size-4" />Back to Help & Support</Link><p className="text-sm font-bold uppercase tracking-[.16em] text-[#54725d]">Admin documentation</p><h2 className="mt-2 text-4xl font-semibold tracking-[-.045em]">How Admiro works</h2><p className="mt-3 max-w-3xl text-[#667069]">Use this guide as the normal operating workflow. The goal is simple: keep applicant records accurate, give clear document feedback, and make sure the right students receive the right updates.</p><section className="mt-8 grid gap-4">{steps.map(({ title, text, icon: Icon }) => <article key={title} className="flex gap-4 rounded-2xl border border-[#dfe3da] bg-white p-5 sm:p-6"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-[#eff4ea] text-[#17351f]"><Icon className="size-5" /></span><div><h3 className="font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#667069]">{text}</p></div></article>)}</section><section className="mt-6 rounded-2xl bg-[#d8ff63] p-6"><h3 className="text-xl font-bold">Daily workflow at a glance</h3><p className="mt-2 text-sm leading-6 text-[#425246]">Start with pending document reviews and open tickets. Then review student records that need action, publish any confirmed university or platform updates, and use Analytics or System Status to check the overall workload.</p></section></div>
}
